language: node_js
node_js:
  - "10"
cache: yarn
install:
  - yarn install --pure-lockfile
script:
  - yarn lint
  - snyk test --severity-threshold=high
  - yarn test
  - yarn build
  - yarn postbuild:lint
