// see https://community.netlify.com/t/common-issue-using-private-npm-modules-on-netlify/795/26
const fs = require('fs');
const { spawnSync } = require('child_process');

// Netlify does not support Github Packages (or other private package registries besides npm), options are:
//   - Commit .npmrc to repo - However, now we have a secret token inside our repo
//   - Environment variable in .npmrc - However, this requires all developer machines to have the same environment variable configured
//   - Get creative with the preinstall script... :)

// Only run this script on Netlify
if (process.env.NETLIFY === 'true') { // this is a default Netlify environment variable
  // Check if .npmrc was already generated by this script. If it does then do nothing (otherwise we create an infinite yarn loop)
  if (process.env.NETLIFY_NPMRC_DONE !== 'true') {
    // Create .npmrc
    fs.writeFileSync('.npmrc', `@fortawesome:registry=https://npm.fontawesome.com/\n//npm.fontawesome.com/:_authToken=${process.env.FA_NPM_TOKEN}`);
    fs.chmodSync('.npmrc', 0o600);
    const text = fs.readFileSync('.npmrc', 'utf8');
    console.log(text);

    // Run yarn again, because the yarn process which is executing
    // this script won't pick up the .npmrc file we just created.
    // The original yarn process will continue after this second yarn process finishes,
    // and when it does it will report "success Already up-to-date.";
    spawnSync('yarn', { stdio: 'inherit', env: { ...process.env, NETLIFY_NPMRC_DONE: true } });
  } else {
    process.exit(1);
  }
}
